### ISSUE TITLE
Should I change parameters when I test on different datasets?

### ISSUE THREAD

**Issue by ftimes** [volpato30/PointNovo#3]
Hi Rui,

I'm trying to quote PointNovo in my work.Before that, I tried to reproduce the results in the paper.

What I want to know is whether I need to make parameter changes when testing the three data sets of "ABRF", "PXD008844" and "PXD010559"? (review the comparison with deepnovo in the paper, Fig. 1. C)

In other words, does that mean they use the same MZ_ MAX,MAX_ LEN and "knapsack.npy" in Fig1. C?

Best,

Xu

**Comment by volpato30** [comment]
Hi,

They use different PTM settings. 

ABRF and PXD010559 has fixed C modification. Oxidation(M) and Deamidation(NQ) as variable modification
PXD008844 has fixed C modification. Oxidation(M) as variable modification.

To change the modifications, you need to modify reverse_vocab in config.py. A different set of PTMs requires a different knapsack.npy file. The safest way is to delete knapsack.npy before run de novo. The program will automatically generate one according to the reverse_vocab in config.py. The generation will take some time though.

Let me know if you have more questions

**Comment by ftimes** [comment]
Thanks!

**Comment by ftimes** [comment]
> Hi,
> 
> They use different PTM settings. 
> 
> ABRF and PXD010559 has fixed C modification. Oxidation(M) and Deamidation(NQ) as variable modification
> PXD008844 has fixed C modification. Oxidation(M) as variable modification.
> 
> To change the modifications, you need to modify reverse_vocab in config.py. A different set of PTMs requires a different knapsack.npy file. The safest way is to delete knapsack.npy before running de novo. The program will automatically generate one according to the reverse_vocab in config.py. The generation will take some time though.
> 
> Let me know if you have more questions
> 

Thanks!
I will try it(^～^) .
